# Financial Constants
MONTHS_PER_YEAR = 12
DAYS_PER_YEAR = 365
PERCENTAGE_DIVISOR = 100

# Default Values
DEFAULT_INITIAL_AMOUNT = 1000.0
DEFAULT_MONTHLY_CONTRIBUTION = 100.0
DEFAULT_ANNUAL_INTEREST_RATE = 5.0
DEFAULT_YEARS = 10

# Rounding
DECIMAL_PLACES = 2
ROUNDING_MODE = 'ROUND_DOWN'  # Options: 'ROUND_DOWN', 'ROUND_UP', 'ROUND_HALF_UP'

# Currency
CURRENCY_SYMBOL = '€'
CURRENCY_CODE = 'EUR'

# Date Formats
DATE_FORMAT = '%d.%m.%Y'
MONTH_YEAR_FORMAT = '%m.%Y'
YEAR_FORMAT = '%Y' 